=begin
MC Camp Featured Project

This is a POC

The version of the OpenAPI document: 1.0.6
Contact: apiteam@swagger.io
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def get_camp_featured_projects
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
